// Render confirmed tokens into a Tailwind v4 `theme.css`.
//
// Components read canonical CSS variables (see tokens.mjs). `eject` writes both a `@theme`
// block (so Tailwind generates utilities) and a `:root` block (so raw var() references and
// non-Tailwind CSS resolve). Only tokens that map to a canonical variable are emitted.

import { cssVariableMap, flattenTokens } from './tokens.mjs'

/**
 * @param {object} tokens token document ({colors, radius, ...})
 * @returns {string} theme.css contents
 */
export function renderThemeCss(tokens) {
  const flat = flattenTokens(tokens)
  const lines = []
  for (const [tokenKey, variable] of Object.entries(cssVariableMap)) {
    if (flat[tokenKey] !== undefined) {
      lines.push(`  ${variable}: ${flat[tokenKey]};`)
    }
  }
  const body = lines.length ? lines.join('\n') : '  /* no tokens to emit yet */'
  return `/* Generated by tessera-ui theme. Edit tokens via tessera-ui.json, then re-run \`tessera-ui theme eject\`. */
@theme {
${body}
}

:root {
${body}
}
`
}
